# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('content', models.TextField(default='')),
                ('category', models.CharField(choices=[('1', 'User verification'), ('2', 'Bug report'), ('3', 'Suggestion'), ('4', 'Review')], default='1', max_length=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
