# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='name',
            field=models.CharField(choices=[(b'1', b'Body building'), (b'14', b'Blogger'), (b'2', b'Dieting'), (b'3', b'Gym'), (b'4', b'Meditation'), (b'5', b'Nutrition'), (b'6', b'Physical exercise'), (b'7', b'Yoga'), (b'8', b'Running'), (b'9', b'Weight lifting'), (b'10', b'Physical fitness'), (b'11', b'Zumba'), (b'12', b'Swimming'), (b'13', b'Other')], max_length=2, primary_key=True, serialize=False),
        ),
    ]
