# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='customers.Profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Profile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('from_user', 'to_user')]),
        ),
    ]
